name: CI TypeScript e Merge Queue

on:
  pull_request:
    branches: [ "main" ]
  merge_group:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Type check
        run: npm run build
      - name: Run tests
        run: npm run test

  approve_merge:
    needs: test
    if: github.event_name == 'merge_group'
    runs-on: ubuntu-latest
    environment: 
      name: producao # Este ambiente será usado para travar a fila no GitHub
    steps:
      - run: echo "Merge manual aprovado pelo revisor na fila de merge!"
